// <auto-generated />
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ShoesDbContext))]
    [Migration("20210114212919_8shoes")]
    partial class _8shoes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DAL.Entities.Dictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("HasBrand")
                        .HasColumnType("bit");

                    b.Property<bool>("HasType")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dictionaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasBrand = false,
                            HasType = true,
                            Title = "Sneakers"
                        },
                        new
                        {
                            Id = 2,
                            HasBrand = false,
                            HasType = true,
                            Title = "Sandals"
                        },
                        new
                        {
                            Id = 3,
                            HasBrand = false,
                            HasType = true,
                            Title = "Boots"
                        },
                        new
                        {
                            Id = 4,
                            HasBrand = false,
                            HasType = true,
                            Title = "Monsters"
                        },
                        new
                        {
                            Id = 5,
                            HasBrand = true,
                            HasType = false,
                            Title = "Nike"
                        },
                        new
                        {
                            Id = 6,
                            HasBrand = true,
                            HasType = false,
                            Title = "Adidas"
                        },
                        new
                        {
                            Id = 7,
                            HasBrand = true,
                            HasType = false,
                            Title = "Puma"
                        },
                        new
                        {
                            Id = 8,
                            HasBrand = true,
                            HasType = false,
                            Title = "Saukoni"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Shoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductionCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 6,
                            Color = "blue",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 100m,
                            ProductionCountry = "Georgia",
                            TypeId = 4
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 5,
                            Color = "gray",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 200m,
                            ProductionCountry = "USA",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 6,
                            Color = "white",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 20m,
                            ProductionCountry = "Chine",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 6,
                            Color = "white",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 20m,
                            ProductionCountry = "China",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 6,
                            Color = "white",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 20m,
                            ProductionCountry = "China",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            Color = "black",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 20m,
                            ProductionCountry = "China",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            Color = "pink",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 20m,
                            ProductionCountry = "China",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            Color = "white",
                            Picture = "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/i1-9cfea66d-b519-4b29-8e43-ce4164e8c558/adapt-bb-2-tie-dye-basketball-shoe-vdFwKS.jpg",
                            Price = 200m,
                            ProductionCountry = "Germany",
                            TypeId = 4
                        });
                });

            modelBuilder.Entity("DAL.Entities.Shoes", b =>
                {
                    b.HasOne("DAL.Entities.Dictionary", "Brand")
                        .WithMany("ShoesBrands")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Dictionary", "Type")
                        .WithMany("ShoesTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DAL.Entities.Dictionary", b =>
                {
                    b.Navigation("ShoesBrands");

                    b.Navigation("ShoesTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
